name: DespliqgueWebSPA
on:
  push:
    branches: [main]

jobs:
  compilar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: instalar jdk 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Construir con maven
      run: mvn -B package --file pom.xml
    - name: Mostrar ubicacion War
      #run: echo "El war se ha generado en";cd target/;pwd;echo -e `ls target/`
      run: echo "El war se ha generado en:";cd target/;pwd;echo "Contenido:";echo -e `ls `
    