name: DespliqgueWebSPA
on:
  push:
    branches: [main]

jobs:
  compilar:
    runs-on: ubuntu-latest
    steps:
    - name: clonar repositorio
    - uses: actions/checkout@v4
    - name: instalar jdk 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Construir con maven
      run: mvn -B package --file pom.xml
    